### ISSUE TITLE
Inverse configuration

### ISSUE THREAD

**Issue by maebert** [DemandCube/flinkhose#38]
```yaml
components:
  LambdaComponent:
    DataCollector:
      key: value
  EMRComponent:
    ...
```
